### PR TITLE
Setup public continuous build #72

### PR DESCRIPTION
**Pull request by rms81**
Issue #72 
Although still work in progress I´m issuing the PR so you can see what I´m doing and give your opinion about it.

### CODE REVIEW

**Comment by dubeaud** [comment]
Just had a quick look on my phone and it looks really good so far!

**Comment by rms81** [comment]
Executing unit tests. The tests are all failing, I thing that the problem is that the Db is not being created and the tests are trying to use it.

Regarding the two last steps of the process. Publish and Archive. I can just convert the nant script to msbuild, but just to make sure that I´m using the right approach, would help to know what is being published and where to. Same thing about Archive.

**Comment by dubeaud** [comment]
I would just disable the unit tests for now. They aren't proper unit tests and they all need to updated.

Publish just copies all the required files to temp directory, and renames the Latest.SqlDataProvider.sql  upgrade script to the proper version number to work with the install / upgrade engine in BugNET.

Archive just packages the all the files up in a zip file, source, install and webdeploy and just need to be available for users to download as build outputs.  

These two steps could be one.

**Comment by dubeaud** [comment]
how is it going with this?

**Comment by rms81** [comment]
Had to stop for a while.
Planning to finish it over this weekend.

**Comment by dubeaud** [comment]
ok great, let me know if you need any help.

**Comment by rms81** [comment]
I think it´s done.
Tried to do most of the work in the msbuild script for easy local testing/debugging of the build script.
All Appveyor configuration is done in appveyor.yml file You just have to create a project in Appveyor pointing to the repository and it should work.
The badge inside readme.md must be changed to point to the new project.
All files in dist folder are added to the build as an artifact that can be downloaded.

**Comment by dubeaud** [comment]
Great I will create an appveyor account and merge everything in.

**Comment by rms81** [comment]
David,

The building badge is still referring to my appveyor project :)

**Comment by dubeaud** [comment]
Thanks. I haven't setup my own appveyor account yet but should be able to today.

**Comment by dubeaud** [comment]
Not sure if I have it configured right or I am missing something but I noticed a few things.

- Appveyor can create the web deploy package by default and can also control the versioning as well as discovering and running unit tests I noticed from the the docs. 
- The result artifact package is a zip file of both the web deploy package and the latest sql script and install notes.  Maybe I missed something in the configuration.

**Pull request merged**
