### PR TITLE
Issues created from mailbox do not fire notifications #82

### PR DESCRIPTION
**Pull request by vmasanas**
Added a few fixes to add notifications for issues created by email.
I've also comment line 172 in IssueNotificationManager:
- it will throw an errow on background threads because there's no active user
- I think this is incorrect, since if the project has a default configured to send notifications to owner, it should still send the email

### CODE REVIEW

**Comment by dubeaud** [comment]
Thanks.  Any idea why the commits are full files and its not showing diff?

**Comment by vmasanas** [comment]
No idea, actually I had quite some trouble with the solution. Don't know why a lot of the files show as modified on my local copy even I haven't touched them (all the files in Lumisoft.net for instance).
I'm sorry but I tried a couple times (even deleted the full repro) and always got the same result.

**Comment by vmasanas** [comment]
BTW, how is your release schedule? I'd like to use these fixes in my installation but not sure if I'll be able to upgrade further if I upgrade to the current version now.

**Comment by dubeaud** [comment]
I think it has to do with line endings, just looking into it now as I am still pretty new to git.

You should be able to use your fixes now but the attachment storage type has changed to be at the global level now and needs migration.  If you just keep with your fixes it should be fine when upgrading to the next release.

**Comment by vmasanas** [comment]
The thing is that I created the fork on the last commit, and my version is the last released one.
So I'll have to modify the DB to incorporate the changes you made or maybe will just create another fork on the release and port my changes there. Probably this is the bes option I think.

**Comment by dubeaud** [comment]
I would suggest forking or cloning off the last release and merge your changes, that way you don't have to deal with the attachment storage type change.

**Comment by vmasanas** [comment]
BTW, if you can figure the issue with the files let me know because this is driving me crazy also here. I have a lot of "modified" files floating around that I cannot manage to get into proper state.

**Comment by dubeaud** [comment]
I believe I fixed the issue in the last few commits and used the github docs to normalize the line endings.

**Comment by vmasanas** [comment]
I did a pull from upstream and still getting trouble with line endings. I want to submit a new fix but I'll be sending the full file again. Any idea on this?

**Comment by vmasanas** [comment]
I think I've figured this out. Please take a look at the new pull request I sent

**Comment by dubeaud** [comment]
Thanks I'll take a look. Cloning / checking out the code again should pick up all the normalized line endings.

**Pull request merged**
